#!/usr/bin/env python3
"""Add eventos and experiencias page sections to translations.ts for all 4 locales."""

with open('src/i18n/translations.ts', encoding='utf-8') as f:
    content = f.read()

# ── EVENTOS sections ─────────────────────────────────────────────────────────

eventos_es = """    eventos: {
      hero_label: "EVENTOS & CELEBRACIONES",
      hero_heading: "Momentos que duran para siempre",
      hero_pill_bodas: "Bodas",
      hero_pill_comuniones: "Comuniones",
      hero_pill_cumpleanos: "Cumpleaños",
      hero_cta: "Descubrir el espacio",
      venue_label: "EL ESPACIO",
      venue_heading: "Un entorno único",
      venue_body1: "Porta D'irta te ofrece un espacio privilegiado donde la naturaleza y la elegancia se encuentran. Nuestros jardines mediterráneos, con palmeras centenarias y buganvillas en flor, crean el escenario perfecto para celebraciones al aire libre. La amplia terraza con vistas al mar Mediterráneo transforma cualquier evento en una experiencia verdaderamente irrepetible.",
      venue_body2: "Disponemos de distintas zonas para adaptarnos a cada tipo de celebración: desde íntimas reuniones familiares hasta grandes banquetes de boda. La pista de tenis, la piscina y los rincones ajardinados ofrecen infinitas posibilidades para que cada detalle refleje exactamente lo que imaginas para tu día especial.",
      feature_capacity_label: "Capacidad",
      feature_capacity_value: "Hasta 120 invitados",
      feature_outdoor_label: "Exterior",
      feature_outdoor_value: "Jardín y terraza",
      feature_sports_label: "Deportes",
      feature_sports_value: "Pista de tenis",
      feature_catering_label: "Gastronomía",
      feature_catering_value: "Restaurante propio",
      types_label: "CELEBRACIONES",
      types_heading: "¿Qué estás celebrando?",
      type_bodas_heading: "Bodas",
      type_bodas_body: "Tu boda en Porta D'irta es mucho más que una ceremonia: es el inicio de una historia inolvidable. Nuestros paquetes nupciales incluyen decoración personalizada, menú de alta gastronomía mediterránea y coordinación total del evento para que solo te preocupes de disfrutar.",
      type_bodas_cta: "Solicitar Información",
      type_comuniones_heading: "Comuniones",
      type_comuniones_body: "Celebra este momento único rodeado de los seres más queridos en un entorno mágico frente al Mediterráneo. Ofrecemos menús especialmente diseñados para todas las edades, animación infantil y espacios adaptados para que los más pequeños disfruten tanto como los mayores.",
      type_comuniones_cta: "Solicitar Información",
      type_private_heading: "Eventos Privados",
      type_private_body: "Desde cumpleaños íntimos hasta cenas de empresa o retiros corporativos, nuestra villa se adapta a cualquier tipo de evento privado. Disponemos de espacios flexibles tanto en interior como en exterior, con tecnología audiovisual y catering a medida para sorprender a tus invitados.",
      type_private_cta: "Solicitar Información",
      upcoming_label: "AGENDA",
      upcoming_heading: "Próximos Eventos en Porta D'irta",
      upcoming_free: "Entrada libre",
      upcoming_buy_tickets: "Comprar Entradas",
      upcoming_more_info: "Más información",
      upcoming_per_person: "/ persona",
      form_label: "CONTACTO",
      form_heading: "Cuéntanos tu evento",
      form_body: "Rellena el formulario y nuestro equipo te contactará para diseñar juntos la celebración perfecta.",
      form_name_label: "Nombre *",
      form_name_placeholder: "Tu nombre completo",
      form_email_label: "Email *",
      form_phone_label: "Teléfono",
      form_type_label: "Tipo de evento *",
      form_type_select: "Selecciona una opción",
      form_type_boda: "Boda",
      form_type_comunion: "Comunión",
      form_type_cumpleanos: "Cumpleaños",
      form_type_corporativo: "Evento corporativo",
      form_type_otro: "Otro",
      form_date_label: "Fecha aproximada",
      form_guests_label: "Número de invitados",
      form_guests_placeholder: "Ej. 80",
      form_message_label: "Mensaje",
      form_message_placeholder: "Cuéntanos tu visión: tipo de celebración, necesidades especiales, preguntas...",
      rgpd_text: "He leído y acepto la",
      rgpd_privacy_link: "Política de Privacidad",
      rgpd_text2: ". Consiento el tratamiento de mis datos para atender mi consulta de evento. *",
      form_submit: "Enviar Consulta",
      form_response_time: "Respondemos en menos de 48 horas · info@portadirta.com",
      form_success: "¡Gracias! Nos pondremos en contacto pronto.",
      form_error: "Ha ocurrido un error. Por favor inténtalo de nuevo o llámanos directamente.",
      crosssell_label: "DESCUBRE MÁS",
      crosssell_hotel: "El Hotel",
      crosssell_restaurante: "El Restaurante",
      crosssell_experiencias: "Experiencias",
    },
"""

eventos_en = """    eventos: {
      hero_label: "EVENTS & CELEBRATIONS",
      hero_heading: "Moments that last forever",
      hero_pill_bodas: "Weddings",
      hero_pill_comuniones: "Communions",
      hero_pill_cumpleanos: "Birthdays",
      hero_cta: "Discover the venue",
      venue_label: "THE VENUE",
      venue_heading: "A unique setting",
      venue_body1: "Porta D'irta offers you a privileged space where nature and elegance meet. Our Mediterranean gardens, with century-old palm trees and blooming bougainvilleas, create the perfect backdrop for outdoor celebrations. The spacious terrace overlooking the Mediterranean Sea transforms any event into a truly unforgettable experience.",
      venue_body2: "We have different areas to suit every type of celebration: from intimate family gatherings to grand wedding banquets. The tennis court, pool, and garden nooks offer endless possibilities so every detail reflects exactly what you envision for your special day.",
      feature_capacity_label: "Capacity",
      feature_capacity_value: "Up to 120 guests",
      feature_outdoor_label: "Outdoor",
      feature_outdoor_value: "Garden and terrace",
      feature_sports_label: "Sports",
      feature_sports_value: "Tennis court",
      feature_catering_label: "Gastronomy",
      feature_catering_value: "In-house restaurant",
      types_label: "CELEBRATIONS",
      types_heading: "What are you celebrating?",
      type_bodas_heading: "Weddings",
      type_bodas_body: "Your wedding at Porta D'irta is much more than a ceremony: it is the beginning of an unforgettable story. Our bridal packages include personalised decoration, a high Mediterranean gastronomy menu, and full event coordination so you only need to enjoy it.",
      type_bodas_cta: "Request Information",
      type_comuniones_heading: "Communions",
      type_comuniones_body: "Celebrate this unique moment surrounded by loved ones in a magical setting overlooking the Mediterranean. We offer specially designed menus for all ages, children's entertainment, and adapted spaces so the little ones enjoy it as much as the adults.",
      type_comuniones_cta: "Request Information",
      type_private_heading: "Private Events",
      type_private_body: "From intimate birthdays to corporate dinners or retreats, our villa adapts to any type of private event. We have flexible spaces both indoors and outdoors, with audiovisual technology and bespoke catering to impress your guests.",
      type_private_cta: "Request Information",
      upcoming_label: "AGENDA",
      upcoming_heading: "Upcoming Events at Porta D'irta",
      upcoming_free: "Free entry",
      upcoming_buy_tickets: "Buy Tickets",
      upcoming_more_info: "More information",
      upcoming_per_person: "/ person",
      form_label: "CONTACT",
      form_heading: "Tell us about your event",
      form_body: "Fill in the form and our team will get in touch to design your perfect celebration together.",
      form_name_label: "Name *",
      form_name_placeholder: "Your full name",
      form_email_label: "Email *",
      form_phone_label: "Phone",
      form_type_label: "Event type *",
      form_type_select: "Select an option",
      form_type_boda: "Wedding",
      form_type_comunion: "Communion",
      form_type_cumpleanos: "Birthday",
      form_type_corporativo: "Corporate event",
      form_type_otro: "Other",
      form_date_label: "Approximate date",
      form_guests_label: "Number of guests",
      form_guests_placeholder: "E.g. 80",
      form_message_label: "Message",
      form_message_placeholder: "Tell us your vision: type of celebration, special needs, questions...",
      rgpd_text: "I have read and accept the",
      rgpd_privacy_link: "Privacy Policy",
      rgpd_text2: ". I consent to the processing of my data to attend my event enquiry. *",
      form_submit: "Send Enquiry",
      form_response_time: "We respond within 48 hours · info@portadirta.com",
      form_success: "Thank you! We will be in touch soon.",
      form_error: "An error occurred. Please try again or call us directly.",
      crosssell_label: "DISCOVER MORE",
      crosssell_hotel: "The Hotel",
      crosssell_restaurante: "The Restaurant",
      crosssell_experiencias: "Experiences",
    },
"""

eventos_fr = """    eventos: {
      hero_label: "ÉVÉNEMENTS & CÉLÉBRATIONS",
      hero_heading: "Des moments qui durent pour toujours",
      hero_pill_bodas: "Mariages",
      hero_pill_comuniones: "Communions",
      hero_pill_cumpleanos: "Anniversaires",
      hero_cta: "Découvrir le lieu",
      venue_label: "LE LIEU",
      venue_heading: "Un cadre unique",
      venue_body1: "Porta D'irta vous offre un espace privilégié où la nature et l'élégance se rencontrent. Nos jardins méditerranéens, avec des palmiers centenaires et des bougainvillées en fleurs, créent le décor parfait pour les célébrations en plein air. La grande terrasse avec vue sur la mer Méditerranée transforme tout événement en une expérience vraiment inoubliable.",
      venue_body2: "Nous disposons de différentes zones pour nous adapter à chaque type de célébration : des réunions familiales intimes aux grands banquets de mariage. Le court de tennis, la piscine et les coins jardinés offrent des possibilités infinies pour que chaque détail reflète exactement ce que vous imaginez pour votre journée spéciale.",
      feature_capacity_label: "Capacité",
      feature_capacity_value: "Jusqu'à 120 invités",
      feature_outdoor_label: "Extérieur",
      feature_outdoor_value: "Jardin et terrasse",
      feature_sports_label: "Sports",
      feature_sports_value: "Court de tennis",
      feature_catering_label: "Gastronomie",
      feature_catering_value: "Restaurant propre",
      types_label: "CÉLÉBRATIONS",
      types_heading: "Qu'est-ce que vous célébrez ?",
      type_bodas_heading: "Mariages",
      type_bodas_body: "Votre mariage à Porta D'irta est bien plus qu'une cérémonie : c'est le début d'une histoire inoubliable. Nos forfaits nuptiaux incluent une décoration personnalisée, un menu de haute gastronomie méditerranéenne et une coordination totale de l'événement pour que vous n'ayez qu'à profiter.",
      type_bodas_cta: "Demander des informations",
      type_comuniones_heading: "Communions",
      type_comuniones_body: "Célébrez ce moment unique entouré de vos proches dans un cadre magique face à la Méditerranée. Nous proposons des menus spécialement conçus pour tous les âges, des animations pour enfants et des espaces adaptés pour que les plus petits profitent autant que les grands.",
      type_comuniones_cta: "Demander des informations",
      type_private_heading: "Événements Privés",
      type_private_body: "Des anniversaires intimes aux dîners d'entreprise ou retraites corporatives, notre villa s'adapte à tout type d'événement privé. Nous disposons d'espaces flexibles en intérieur et en extérieur, avec technologie audiovisuelle et traiteur sur mesure pour impressionner vos invités.",
      type_private_cta: "Demander des informations",
      upcoming_label: "AGENDA",
      upcoming_heading: "Prochains Événements à Porta D'irta",
      upcoming_free: "Entrée libre",
      upcoming_buy_tickets: "Acheter des billets",
      upcoming_more_info: "Plus d'informations",
      upcoming_per_person: "/ personne",
      form_label: "CONTACT",
      form_heading: "Parlez-nous de votre événement",
      form_body: "Remplissez le formulaire et notre équipe vous contactera pour concevoir ensemble la célébration parfaite.",
      form_name_label: "Nom *",
      form_name_placeholder: "Votre nom complet",
      form_email_label: "Email *",
      form_phone_label: "Téléphone",
      form_type_label: "Type d'événement *",
      form_type_select: "Sélectionnez une option",
      form_type_boda: "Mariage",
      form_type_comunion: "Communion",
      form_type_cumpleanos: "Anniversaire",
      form_type_corporativo: "Événement d'entreprise",
      form_type_otro: "Autre",
      form_date_label: "Date approximative",
      form_guests_label: "Nombre d'invités",
      form_guests_placeholder: "Ex. 80",
      form_message_label: "Message",
      form_message_placeholder: "Parlez-nous de votre vision : type de célébration, besoins spéciaux, questions...",
      rgpd_text: "J'ai lu et j'accepte la",
      rgpd_privacy_link: "Politique de confidentialité",
      rgpd_text2: ". Je consens au traitement de mes données pour répondre à ma demande d'événement. *",
      form_submit: "Envoyer la demande",
      form_response_time: "Nous répondons dans les 48 heures · info@portadirta.com",
      form_success: "Merci ! Nous vous contacterons bientôt.",
      form_error: "Une erreur s'est produite. Veuillez réessayer ou nous appeler directement.",
      crosssell_label: "DÉCOUVRIR PLUS",
      crosssell_hotel: "L'Hôtel",
      crosssell_restaurante: "Le Restaurant",
      crosssell_experiencias: "Expériences",
    },
"""

eventos_de = """    eventos: {
      hero_label: "VERANSTALTUNGEN & FEIERN",
      hero_heading: "Momente, die für immer bleiben",
      hero_pill_bodas: "Hochzeiten",
      hero_pill_comuniones: "Kommunionen",
      hero_pill_cumpleanos: "Geburtstage",
      hero_cta: "Das Gelände entdecken",
      venue_label: "DAS GELÄNDE",
      venue_heading: "Ein einzigartiger Rahmen",
      venue_body1: "Porta D'irta bietet Ihnen einen privilegierten Raum, wo Natur und Eleganz aufeinandertreffen. Unsere mediterranen Gärten mit jahrhundertealten Palmen und blühenden Bougainvilleen schaffen die perfekte Kulisse für Freiluftfeiern. Die große Terrasse mit Blick auf das Mittelmeer verwandelt jede Veranstaltung in ein wirklich unvergessliches Erlebnis.",
      venue_body2: "Wir verfügen über verschiedene Bereiche, um uns an jeden Feiertyp anzupassen: von intimen Familientreffen bis hin zu großen Hochzeitsbanketten. Der Tennisplatz, der Pool und die Gartenecken bieten unendliche Möglichkeiten, damit jedes Detail genau das widerspiegelt, was Sie sich für Ihren besonderen Tag vorstellen.",
      feature_capacity_label: "Kapazität",
      feature_capacity_value: "Bis zu 120 Gäste",
      feature_outdoor_label: "Außenbereich",
      feature_outdoor_value: "Garten und Terrasse",
      feature_sports_label: "Sport",
      feature_sports_value: "Tennisplatz",
      feature_catering_label: "Gastronomie",
      feature_catering_value: "Eigenes Restaurant",
      types_label: "FEIERN",
      types_heading: "Was feiern Sie?",
      type_bodas_heading: "Hochzeiten",
      type_bodas_body: "Ihre Hochzeit in Porta D'irta ist viel mehr als eine Zeremonie: Es ist der Beginn einer unvergesslichen Geschichte. Unsere Hochzeitspakete beinhalten persönliche Dekoration, ein Menü der hohen mediterranen Gastronomie und eine vollständige Veranstaltungskoordination, damit Sie sich nur um das Genießen kümmern müssen.",
      type_bodas_cta: "Informationen anfordern",
      type_comuniones_heading: "Kommunionen",
      type_comuniones_body: "Feiern Sie diesen einzigartigen Moment umgeben von Ihren Liebsten in einem magischen Ambiente mit Blick aufs Mittelmeer. Wir bieten speziell entworfene Menüs für alle Altersgruppen, Kinderanimation und angepasste Räume, damit die Kleinen genauso viel Spaß haben wie die Großen.",
      type_comuniones_cta: "Informationen anfordern",
      type_private_heading: "Privatveranstaltungen",
      type_private_body: "Von intimen Geburtstagsfeiern bis zu Firmendinners oder Unternehmensretreats passt sich unsere Villa an jeden Typ von Privatveranstaltung an. Wir verfügen über flexible Innen- und Außenräume mit audiovisueller Technologie und maßgeschneidertem Catering, um Ihre Gäste zu beeindrucken.",
      type_private_cta: "Informationen anfordern",
      upcoming_label: "AGENDA",
      upcoming_heading: "Kommende Veranstaltungen in Porta D'irta",
      upcoming_free: "Freier Eintritt",
      upcoming_buy_tickets: "Tickets kaufen",
      upcoming_more_info: "Mehr Informationen",
      upcoming_per_person: "/ Person",
      form_label: "KONTAKT",
      form_heading: "Erzählen Sie uns von Ihrer Veranstaltung",
      form_body: "Füllen Sie das Formular aus und unser Team kontaktiert Sie, um gemeinsam die perfekte Feier zu gestalten.",
      form_name_label: "Name *",
      form_name_placeholder: "Ihr vollständiger Name",
      form_email_label: "E-Mail *",
      form_phone_label: "Telefon",
      form_type_label: "Veranstaltungstyp *",
      form_type_select: "Option auswählen",
      form_type_boda: "Hochzeit",
      form_type_comunion: "Kommunion",
      form_type_cumpleanos: "Geburtstag",
      form_type_corporativo: "Firmenveranstaltung",
      form_type_otro: "Sonstiges",
      form_date_label: "Ungefähres Datum",
      form_guests_label: "Anzahl der Gäste",
      form_guests_placeholder: "Z.B. 80",
      form_message_label: "Nachricht",
      form_message_placeholder: "Erzählen Sie uns Ihre Vision: Art der Feier, besondere Wünsche, Fragen...",
      rgpd_text: "Ich habe die gelesen und akzeptiere sie",
      rgpd_privacy_link: "Datenschutzbestimmungen",
      rgpd_text2: ". Ich willige in die Verarbeitung meiner Daten für meine Veranstaltungsanfrage ein. *",
      form_submit: "Anfrage senden",
      form_response_time: "Wir antworten innerhalb von 48 Stunden · info@portadirta.com",
      form_success: "Vielen Dank! Wir werden uns bald melden.",
      form_error: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut oder rufen Sie uns direkt an.",
      crosssell_label: "MEHR ENTDECKEN",
      crosssell_hotel: "Das Hotel",
      crosssell_restaurante: "Das Restaurant",
      crosssell_experiencias: "Erlebnisse",
    },
"""

# ── EXPERIENCIAS sections ────────────────────────────────────────────────────

experiencias_es = """    experiencias: {
      hero_label: "EXPERIENCIAS",
      hero_heading: "Descubre la Costa del Azahar",
      hero_subtitle: "Excursiones, gastronomía y aventuras diseñadas para nuestros huéspedes",
      hero_pill_naturaleza: "Naturaleza",
      hero_pill_mar: "Mar",
      hero_pill_cultura: "Cultura",
      hero_pill_gastronomia: "Gastronomía",
      hero_cta: "Descubrir experiencias",
      intro_label: "PARA NUESTROS HUÉSPEDES",
      intro_heading: "Todo lo que Peñíscola tiene que ofrecerte",
      intro_body1: "En Porta D'irta creemos que una estancia perfecta va mucho más allá de las comodidades de la villa. Por eso hemos seleccionado las mejores experiencias de la Costa del Azahar y las hemos organizado exclusivamente para nuestros huéspedes, desde rutas de montaña en la Sierra de Irta hasta aventuras acuáticas en el Mediterráneo cristalino.",
      intro_body2: "Trabajamos con guías locales certificados y colaboradores de confianza para garantizarte autenticidad, seguridad y momentos únicos. Solo tienes que decirnos qué te apetece y nuestro equipo lo organiza todo: recogida, reservas y hasta la cesta de picnic para el camino.",
      packages_label: "RESERVA TU EXPERIENCIA",
      packages_heading: "Nuestros Paquetes",
      packages_body: "Plazas limitadas. Reserva con antelación para garantizar tu experiencia.",
      packages_empty: "Próximamente nuevas experiencias",
      packages_empty_body: "Estamos preparando nuevos paquetes para la próxima temporada. Contacta con nosotros para más información.",
      packages_contact: "Contactar",
      packages_book: "Reservar",
      packages_finished: "Finalizado",
      packages_from_price: "desde €{price}/persona",
      packages_enquire: "Consultar precio",
      sierra_label: "NATURALEZA",
      sierra_heading: "Sierra de Irta",
      sierra_body1: "El Parque Natural de la Sierra de Irta es uno de los últimos tramos de litoral virgen del Mediterráneo español. Con más de 5.000 hectáreas de monte bajo, acantilados y calas secretas, es el escenario ideal para conectar con la naturaleza a pocos minutos de la villa.",
      sierra_body2: "Nuestros guías locales te llevan por los senderos más espectaculares, adaptando el recorrido a tu nivel físico y tus intereses. Una experiencia que combina paisaje, historia y biodiversidad en estado puro.",
      sierra_act1: "Senderismo guiado",
      sierra_act2: "Rutas en bicicleta",
      sierra_act3: "Observación de aves",
      sierra_act4: "Fotografía de naturaleza",
      sierra_cta: "Reservar Excursión",
      sea_label: "MAR & PLAYA",
      sea_heading: "El Mediterráneo a tu puerta",
      cultura_label: "CULTURA & GASTRONOMÍA",
      cultura_heading: "Peñíscola, historia y sabor",
      cultura_peniscola_heading: "Peñíscola Histórica",
      cultura_peniscola_body: "Descubre los secretos del castillo templario donde el Papa Luna escribió sus bulas, y pasea por las callejuelas empedradas de la ciudad amurallada. Nuestros guías locales dan vida a siglos de historia medieval, árabe y cristiana en un recorrido personalizado a tu ritmo.",
      cultura_peniscola_cta: "Explorar",
      cultura_vinos_heading: "Cata de Vinos & Gastronomía",
      cultura_vinos_body: "Cata guiada de cuatro vinos D.O. Valencia con maridaje de productos locales. El sumiller del restaurante os guiará por la historia, aromas y sabores de la terra. Cupos muy limitados — máximo 12 personas para una experiencia íntima.",
      cultura_vinos_cta: "Explorar",
      partners_label: "COLABORADORES",
      partners_heading: "Nuestros colaboradores locales",
      partners_subtitle: "Trabajamos con los mejores proveedores de la zona para ofrecerte experiencias auténticas",
      form_label: "PLANIFICA TU ESTANCIA",
      form_heading: "Diseña tu experiencia perfecta",
      form_body: "Cuéntanos qué te apetece y lo organizamos todo por ti",
      form_name_label: "Nombre *",
      form_name_placeholder: "Tu nombre completo",
      form_email_label: "Email *",
      form_phone_label: "Teléfono",
      form_type_label: "Tipo de experiencia *",
      form_type_select: "Selecciona una opción",
      form_type_sierra: "Sierra de Irta",
      form_type_acuaticas: "Actividades Acuáticas",
      form_type_cultura: "Cultura & Historia",
      form_type_gastronomia: "Gastronomía",
      form_type_combinacion: "Combinación personalizada",
      form_date_label: "Fecha de llegada",
      form_guests_label: "Nº personas",
      form_guests_placeholder: "Ej. 4",
      form_message_label: "Mensaje especial",
      form_message_placeholder: "Cuéntanos tus preferencias, nivel físico, alergias alimentarias o cualquier detalle especial...",
      rgpd_text: "He leído y acepto la",
      rgpd_privacy_link: "Política de Privacidad",
      rgpd_text2: ". Consiento el tratamiento de mis datos para gestionar mi solicitud de experiencia. *",
      form_submit: "Planificar mi Experiencia",
      form_response_time: "Incluido en estancias de 3 noches o más · Resto bajo reserva previa",
      form_success: "¡Gracias! Hemos recibido tu consulta.",
      form_success_body: "Nos pondremos en contacto contigo en menos de 24 horas para organizar tu experiencia.",
      form_error: "Ha ocurrido un error. Por favor inténtalo de nuevo o llámanos directamente.",
      crosssell_label: "DESCUBRE MÁS",
      crosssell_hotel: "El Hotel",
      crosssell_restaurante: "El Restaurante",
      crosssell_eventos: "Eventos & Celebraciones",
    },
"""

experiencias_en = """    experiencias: {
      hero_label: "EXPERIENCES",
      hero_heading: "Discover the Costa del Azahar",
      hero_subtitle: "Excursions, gastronomy and adventures designed for our guests",
      hero_pill_naturaleza: "Nature",
      hero_pill_mar: "Sea",
      hero_pill_cultura: "Culture",
      hero_pill_gastronomia: "Gastronomy",
      hero_cta: "Discover experiences",
      intro_label: "FOR OUR GUESTS",
      intro_heading: "Everything Peñíscola has to offer you",
      intro_body1: "At Porta D'irta we believe a perfect stay goes far beyond the villa's comforts. That is why we have selected the best experiences on the Costa del Azahar, exclusively organised for our guests, from mountain trails in the Sierra de Irta to water adventures in the crystal-clear Mediterranean.",
      intro_body2: "We work with certified local guides and trusted partners to guarantee authenticity, safety and unique moments. Just tell us what you fancy and our team organises everything: pick-up, reservations, and even the picnic basket for the road.",
      packages_label: "BOOK YOUR EXPERIENCE",
      packages_heading: "Our Packages",
      packages_body: "Limited spots. Book in advance to guarantee your experience.",
      packages_empty: "New experiences coming soon",
      packages_empty_body: "We are preparing new packages for the next season. Contact us for more information.",
      packages_contact: "Contact us",
      packages_book: "Book",
      packages_finished: "Finished",
      packages_from_price: "from €{price}/person",
      packages_enquire: "Enquire about price",
      sierra_label: "NATURE",
      sierra_heading: "Sierra de Irta",
      sierra_body1: "The Sierra de Irta Natural Park is one of the last stretches of virgin coastline in the Spanish Mediterranean. With more than 5,000 hectares of scrubland, cliffs, and secret coves, it is the ideal setting to connect with nature just minutes from the villa.",
      sierra_body2: "Our local guides take you along the most spectacular trails, adapting the route to your fitness level and interests. An experience that combines landscape, history, and biodiversity in its purest form.",
      sierra_act1: "Guided hiking",
      sierra_act2: "Cycling routes",
      sierra_act3: "Bird watching",
      sierra_act4: "Nature photography",
      sierra_cta: "Book Excursion",
      sea_label: "SEA & BEACH",
      sea_heading: "The Mediterranean on your doorstep",
      cultura_label: "CULTURE & GASTRONOMY",
      cultura_heading: "Peñíscola, history and flavour",
      cultura_peniscola_heading: "Historic Peñíscola",
      cultura_peniscola_body: "Discover the secrets of the Templar castle where Pope Luna wrote his papal bulls, and stroll through the cobbled streets of the walled city. Our local guides bring centuries of medieval, Arab, and Christian history to life in a personalised tour at your own pace.",
      cultura_peniscola_cta: "Explore",
      cultura_vinos_heading: "Wine Tasting & Gastronomy",
      cultura_vinos_body: "Guided tasting of four D.O. Valencia wines paired with local products. The restaurant's sommelier will guide you through the history, aromas, and flavours of the terra. Very limited spots — maximum 12 people for an intimate experience.",
      cultura_vinos_cta: "Explore",
      partners_label: "PARTNERS",
      partners_heading: "Our local partners",
      partners_subtitle: "We work with the best local suppliers to offer you authentic experiences",
      form_label: "PLAN YOUR STAY",
      form_heading: "Design your perfect experience",
      form_body: "Tell us what you fancy and we will organise everything for you",
      form_name_label: "Name *",
      form_name_placeholder: "Your full name",
      form_email_label: "Email *",
      form_phone_label: "Phone",
      form_type_label: "Experience type *",
      form_type_select: "Select an option",
      form_type_sierra: "Sierra de Irta",
      form_type_acuaticas: "Water Activities",
      form_type_cultura: "Culture & History",
      form_type_gastronomia: "Gastronomy",
      form_type_combinacion: "Custom combination",
      form_date_label: "Arrival date",
      form_guests_label: "No. of people",
      form_guests_placeholder: "E.g. 4",
      form_message_label: "Special message",
      form_message_placeholder: "Tell us your preferences, fitness level, food allergies or any special detail...",
      rgpd_text: "I have read and accept the",
      rgpd_privacy_link: "Privacy Policy",
      rgpd_text2: ". I consent to the processing of my data to manage my experience request. *",
      form_submit: "Plan my Experience",
      form_response_time: "Included with stays of 3 nights or more · Otherwise by prior reservation",
      form_success: "Thank you! We have received your enquiry.",
      form_success_body: "We will get in touch within 24 hours to organise your experience.",
      form_error: "An error occurred. Please try again or call us directly.",
      crosssell_label: "DISCOVER MORE",
      crosssell_hotel: "The Hotel",
      crosssell_restaurante: "The Restaurant",
      crosssell_eventos: "Events & Celebrations",
    },
"""

experiencias_fr = """    experiencias: {
      hero_label: "EXPÉRIENCES",
      hero_heading: "Découvrez la Costa del Azahar",
      hero_subtitle: "Excursions, gastronomie et aventures conçues pour nos hôtes",
      hero_pill_naturaleza: "Nature",
      hero_pill_mar: "Mer",
      hero_pill_cultura: "Culture",
      hero_pill_gastronomia: "Gastronomie",
      hero_cta: "Découvrir les expériences",
      intro_label: "POUR NOS HÔTES",
      intro_heading: "Tout ce que Peñíscola a à vous offrir",
      intro_body1: "À Porta D'irta, nous croyons qu'un séjour parfait va bien au-delà du confort de la villa. C'est pourquoi nous avons sélectionné les meilleures expériences de la Costa del Azahar et les avons organisées exclusivement pour nos hôtes, des randonnées en montagne dans la Sierra de Irta aux aventures nautiques en Méditerranée cristalline.",
      intro_body2: "Nous travaillons avec des guides locaux certifiés et des collaborateurs de confiance pour vous garantir authenticité, sécurité et moments uniques. Il vous suffit de nous dire ce qui vous fait envie et notre équipe organise tout : transfert, réservations et même le panier pique-nique pour la route.",
      packages_label: "RÉSERVEZ VOTRE EXPÉRIENCE",
      packages_heading: "Nos Forfaits",
      packages_body: "Places limitées. Réservez à l'avance pour garantir votre expérience.",
      packages_empty: "De nouvelles expériences arrivent bientôt",
      packages_empty_body: "Nous préparons de nouveaux forfaits pour la prochaine saison. Contactez-nous pour plus d'informations.",
      packages_contact: "Nous contacter",
      packages_book: "Réserver",
      packages_finished: "Terminé",
      packages_from_price: "à partir de €{price}/personne",
      packages_enquire: "Demander le prix",
      sierra_label: "NATURE",
      sierra_heading: "Sierra de Irta",
      sierra_body1: "Le Parc Naturel de la Sierra de Irta est l'un des derniers tronçons de littoral vierge de la Méditerranée espagnole. Avec plus de 5 000 hectares de garrigue, de falaises et de criques secrètes, c'est le cadre idéal pour se connecter avec la nature à quelques minutes de la villa.",
      sierra_body2: "Nos guides locaux vous emmènent sur les sentiers les plus spectaculaires, en adaptant le parcours à votre niveau physique et vos intérêts. Une expérience qui combine paysage, histoire et biodiversité à l'état pur.",
      sierra_act1: "Randonnée guidée",
      sierra_act2: "Circuits à vélo",
      sierra_act3: "Observation des oiseaux",
      sierra_act4: "Photographie nature",
      sierra_cta: "Réserver l'excursion",
      sea_label: "MER & PLAGE",
      sea_heading: "La Méditerranée à votre porte",
      cultura_label: "CULTURE & GASTRONOMIE",
      cultura_heading: "Peñíscola, histoire et saveurs",
      cultura_peniscola_heading: "Peñíscola Historique",
      cultura_peniscola_body: "Découvrez les secrets du château templier où le Pape Luna rédigeait ses bulles pontificales, et promenez-vous dans les ruelles pavées de la ville fortifiée. Nos guides locaux font revivre des siècles d'histoire médiévale, arabe et chrétienne lors d'une visite personnalisée à votre rythme.",
      cultura_peniscola_cta: "Explorer",
      cultura_vinos_heading: "Dégustation de vins & Gastronomie",
      cultura_vinos_body: "Dégustation guidée de quatre vins D.O. Valencia avec des accords mets-vins locaux. Le sommelier du restaurant vous guidera à travers l'histoire, les arômes et les saveurs de la terra. Places très limitées — maximum 12 personnes pour une expérience intime.",
      cultura_vinos_cta: "Explorer",
      partners_label: "PARTENAIRES",
      partners_heading: "Nos partenaires locaux",
      partners_subtitle: "Nous travaillons avec les meilleurs fournisseurs locaux pour vous offrir des expériences authentiques",
      form_label: "PLANIFIEZ VOTRE SÉJOUR",
      form_heading: "Concevez votre expérience parfaite",
      form_body: "Dites-nous ce qui vous fait envie et nous organisons tout pour vous",
      form_name_label: "Nom *",
      form_name_placeholder: "Votre nom complet",
      form_email_label: "Email *",
      form_phone_label: "Téléphone",
      form_type_label: "Type d'expérience *",
      form_type_select: "Sélectionnez une option",
      form_type_sierra: "Sierra de Irta",
      form_type_acuaticas: "Activités nautiques",
      form_type_cultura: "Culture & Histoire",
      form_type_gastronomia: "Gastronomie",
      form_type_combinacion: "Combinaison personnalisée",
      form_date_label: "Date d'arrivée",
      form_guests_label: "Nb de personnes",
      form_guests_placeholder: "Ex. 4",
      form_message_label: "Message spécial",
      form_message_placeholder: "Parlez-nous de vos préférences, niveau physique, allergies alimentaires ou tout détail spécial...",
      rgpd_text: "J'ai lu et j'accepte la",
      rgpd_privacy_link: "Politique de confidentialité",
      rgpd_text2: ". Je consens au traitement de mes données pour gérer ma demande d'expérience. *",
      form_submit: "Planifier mon Expérience",
      form_response_time: "Inclus pour les séjours de 3 nuits ou plus · Sinon sur réservation préalable",
      form_success: "Merci ! Nous avons bien reçu votre demande.",
      form_success_body: "Nous vous contacterons dans les 24 heures pour organiser votre expérience.",
      form_error: "Une erreur s'est produite. Veuillez réessayer ou nous appeler directement.",
      crosssell_label: "DÉCOUVRIR PLUS",
      crosssell_hotel: "L'Hôtel",
      crosssell_restaurante: "Le Restaurant",
      crosssell_eventos: "Événements & Célébrations",
    },
"""

experiencias_de = """    experiencias: {
      hero_label: "ERLEBNISSE",
      hero_heading: "Entdecken Sie die Costa del Azahar",
      hero_subtitle: "Ausflüge, Gastronomie und Abenteuer für unsere Gäste",
      hero_pill_naturaleza: "Natur",
      hero_pill_mar: "Meer",
      hero_pill_cultura: "Kultur",
      hero_pill_gastronomia: "Gastronomie",
      hero_cta: "Erlebnisse entdecken",
      intro_label: "FÜR UNSERE GÄSTE",
      intro_heading: "Alles, was Peñíscola zu bieten hat",
      intro_body1: "Bei Porta D'irta glauben wir, dass ein perfekter Aufenthalt weit über den Komfort der Villa hinausgeht. Deshalb haben wir die besten Erlebnisse der Costa del Azahar ausgewählt und exklusiv für unsere Gäste organisiert, von Bergwanderungen in der Sierra de Irta bis hin zu Wasserabenteuern im kristallklaren Mittelmeer.",
      intro_body2: "Wir arbeiten mit zertifizierten lokalen Guides und vertrauenswürdigen Partnern zusammen, um Ihnen Authentizität, Sicherheit und einzigartige Momente zu garantieren. Sagen Sie uns einfach, was Ihnen gefällt, und unser Team organisiert alles: Abholung, Reservierungen und sogar den Picknickkorb für unterwegs.",
      packages_label: "ERLEBEN SIE BUCHEN",
      packages_heading: "Unsere Pakete",
      packages_body: "Begrenzte Plätze. Buchen Sie im Voraus, um Ihr Erlebnis zu sichern.",
      packages_empty: "Neue Erlebnisse kommen bald",
      packages_empty_body: "Wir bereiten neue Pakete für die nächste Saison vor. Kontaktieren Sie uns für weitere Informationen.",
      packages_contact: "Kontaktieren",
      packages_book: "Buchen",
      packages_finished: "Beendet",
      packages_from_price: "ab €{price}/Person",
      packages_enquire: "Preis anfragen",
      sierra_label: "NATUR",
      sierra_heading: "Sierra de Irta",
      sierra_body1: "Der Naturpark Sierra de Irta ist einer der letzten unberührten Küstenstreifen des spanischen Mittelmeers. Mit mehr als 5.000 Hektar Macchia, Klippen und geheimen Buchten ist er der ideale Ort, um die Natur nur wenige Minuten von der Villa entfernt zu erleben.",
      sierra_body2: "Unsere lokalen Guides führen Sie über die spektakulärsten Pfade und passen die Route an Ihr Fitnessniveau und Ihre Interessen an. Ein Erlebnis, das Landschaft, Geschichte und Artenvielfalt in ihrer reinsten Form vereint.",
      sierra_act1: "Geführte Wanderung",
      sierra_act2: "Fahrradtouren",
      sierra_act3: "Vogelbeobachtung",
      sierra_act4: "Naturfotografie",
      sierra_cta: "Ausflug buchen",
      sea_label: "MEER & STRAND",
      sea_heading: "Das Mittelmeer vor Ihrer Haustür",
      cultura_label: "KULTUR & GASTRONOMIE",
      cultura_heading: "Peñíscola, Geschichte und Geschmack",
      cultura_peniscola_heading: "Historisches Peñíscola",
      cultura_peniscola_body: "Entdecken Sie die Geheimnisse der Templerburg, wo Papst Luna seine päpstlichen Bullen schrieb, und schlendern Sie durch die gepflasterten Gassen der Altstadt. Unsere lokalen Guides erwecken Jahrhunderte mittelalterlicher, arabischer und christlicher Geschichte bei einer personalisierten Tour in Ihrem eigenen Tempo zum Leben.",
      cultura_peniscola_cta: "Erkunden",
      cultura_vinos_heading: "Weinverkostung & Gastronomie",
      cultura_vinos_body: "Geführte Verkostung von vier D.O. Valencia Weinen mit lokalen Produkten. Der Sommelier des Restaurants führt Sie durch die Geschichte, Aromen und Geschmäcker der terra. Sehr begrenzte Plätze — maximal 12 Personen für ein intimes Erlebnis.",
      cultura_vinos_cta: "Erkunden",
      partners_label: "PARTNER",
      partners_heading: "Unsere lokalen Partner",
      partners_subtitle: "Wir arbeiten mit den besten lokalen Anbietern zusammen, um Ihnen authentische Erlebnisse zu bieten",
      form_label: "PLANEN SIE IHREN AUFENTHALT",
      form_heading: "Gestalten Sie Ihr perfektes Erlebnis",
      form_body: "Sagen Sie uns, was Ihnen gefällt, und wir organisieren alles für Sie",
      form_name_label: "Name *",
      form_name_placeholder: "Ihr vollständiger Name",
      form_email_label: "E-Mail *",
      form_phone_label: "Telefon",
      form_type_label: "Erlebnistyp *",
      form_type_select: "Option auswählen",
      form_type_sierra: "Sierra de Irta",
      form_type_acuaticas: "Wasseraktivitäten",
      form_type_cultura: "Kultur & Geschichte",
      form_type_gastronomia: "Gastronomie",
      form_type_combinacion: "Individuelle Kombination",
      form_date_label: "Anreisedatum",
      form_guests_label: "Anzahl Personen",
      form_guests_placeholder: "Z.B. 4",
      form_message_label: "Besondere Nachricht",
      form_message_placeholder: "Erzählen Sie uns Ihre Präferenzen, Fitnessniveau, Lebensmittelallergien oder besondere Details...",
      rgpd_text: "Ich habe die gelesen und akzeptiere sie",
      rgpd_privacy_link: "Datenschutzbestimmungen",
      rgpd_text2: ". Ich willige in die Verarbeitung meiner Daten für meine Erlebnisanfrage ein. *",
      form_submit: "Mein Erlebnis planen",
      form_response_time: "Im Aufenthalt von 3 Nächten oder mehr inklusive · Ansonsten auf Voranmeldung",
      form_success: "Vielen Dank! Wir haben Ihre Anfrage erhalten.",
      form_success_body: "Wir werden uns innerhalb von 24 Stunden melden, um Ihr Erlebnis zu organisieren.",
      form_error: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut oder rufen Sie uns direkt an.",
      crosssell_label: "MEHR ENTDECKEN",
      crosssell_hotel: "Das Hotel",
      crosssell_restaurante: "Das Restaurant",
      crosssell_eventos: "Veranstaltungen & Feiern",
    },
"""

# Insert before each locale's footer section using unique anchor strings
insertions = [
    # (search_string, eventos_block, experiencias_block)
    (
        '    footer: {\n      nav_title: "Navegación",',
        eventos_es,
        experiencias_es,
    ),
    (
        '    footer: {\n      nav_title: "Navigation",\n      contact_title: "Contact",\n      rights: "© 2026 Porta D\'irta. All rights reserved.",',
        eventos_en,
        experiencias_en,
    ),
    (
        '    footer: {\n      nav_title: "Navigation",\n      contact_title: "Contact",\n      rights: "© 2026 Porta D\'irta. Tous droits réservés.",',
        eventos_fr,
        experiencias_fr,
    ),
    (
        '    footer: {\n      nav_title: "Navigation",\n      contact_title: "Kontakt",',
        eventos_de,
        experiencias_de,
    ),
]

for anchor, ev_block, exp_block in insertions:
    assert content.count(anchor) == 1, f"Anchor not unique: {anchor[:60]!r} (found {content.count(anchor)})"
    content = content.replace(anchor, ev_block + exp_block + anchor, 1)

with open('src/i18n/translations.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("eventos + experiencias sections added to all 4 locales.")
